module.exports = {
  url: "https://southafricasdr.com",
  name: "South Africa SDR",
  llmsTxtUrl: "https://southafricasdr.com/llms.txt",
  buildDate: new Date().toISOString().slice(0, 10),
  blogPageSize: 15,
  sitemapPriorities: {
    "/": "1.0",
    "/why-south-africa/": "0.9",
    "/about/": "0.8",
    "/contact/": "0.9",
    "/book/": "0.9",
    "/faq/": "0.8",
    "/services/": "0.9",
    "/services/sdr/": "0.9",
    "/services/appointment-setting/": "0.8",
    "/services/customer-service/": "0.7",
    "/services/technical-support/": "0.7",
    "/industries/": "0.8",
    "/industries/saas/": "0.7",
    "/industries/financial-services/": "0.7",
    "/industries/real-estate/": "0.7",
    "/industries/insurance/": "0.7",
    "/industries/healthcare/": "0.7",
    "/industries/recruitment/": "0.7",
    "/industries/professional-services/": "0.7",
    "/industries/technology-it/": "0.7",
    "/industries/marketing-agencies/": "0.7",
    "/industries/logistics/": "0.7",
    "/industries/manufacturing/": "0.7",
    "/industries/cybersecurity/": "0.7",
    "/compare/south-africa-vs-philippines/": "0.8",
    "/compare/south-africa-vs-india/": "0.8",
    "/compare/south-africa-vs-latin-america/": "0.8",
    "/compare/south-africa-vs-eastern-europe/": "0.8",
    "/compare/in-house-vs-outsourced/": "0.8",
    "/case-studies/": "0.8",
    "/case-studies/saas-pipeline-case-study/": "0.7",
    "/case-studies/fintech-appointment-setting/": "0.7",
    "/privacy/": "0.3",
    "/terms/": "0.3",
    "/cookies/": "0.3",
  },
  staticPaths: [
    "/",
    "/why-south-africa/",
    "/about/",
    "/contact/",
    "/book/",
    "/faq/",
    "/services/",
    "/services/sdr/",
    "/services/appointment-setting/",
    "/services/customer-service/",
    "/services/technical-support/",
    "/industries/",
    "/industries/saas/",
    "/industries/financial-services/",
    "/industries/real-estate/",
    "/industries/insurance/",
    "/industries/healthcare/",
    "/industries/recruitment/",
    "/industries/professional-services/",
    "/industries/technology-it/",
    "/industries/marketing-agencies/",
    "/industries/logistics/",
    "/industries/manufacturing/",
    "/industries/cybersecurity/",
    "/compare/south-africa-vs-philippines/",
    "/compare/south-africa-vs-india/",
    "/compare/south-africa-vs-latin-america/",
    "/compare/south-africa-vs-eastern-europe/",
    "/compare/in-house-vs-outsourced/",
    "/case-studies/",
    "/case-studies/saas-pipeline-case-study/",
    "/case-studies/fintech-appointment-setting/",
    "/privacy/",
    "/terms/",
    "/cookies/",
  ],
};
