module.exports = {
  url: "https://southafricasdr.com",
  name: "South Africa SDR",
  buildDate: new Date().toISOString().slice(0, 10),
  blogPageSize: 15,
  staticPaths: [
    "/",
    "/why-south-africa/",
    "/about/",
    "/contact/",
    "/book/",
    "/faq/",
    "/services/",
    "/services/sdr/",
    "/services/appointment-setting/",
    "/services/customer-service/",
    "/services/technical-support/",
    "/industries/",
    "/industries/saas/",
    "/industries/financial-services/",
    "/industries/real-estate/",
    "/industries/insurance/",
    "/industries/healthcare/",
    "/industries/recruitment/",
    "/industries/professional-services/",
    "/industries/technology-it/",
    "/industries/marketing-agencies/",
    "/industries/logistics/",
    "/industries/manufacturing/",
    "/industries/cybersecurity/",
    "/compare/",
    "/compare/south-africa-vs-philippines/",
    "/compare/south-africa-vs-india/",
    "/compare/south-africa-vs-latin-america/",
    "/compare/south-africa-vs-eastern-europe/",
    "/compare/in-house-vs-outsourced/",
    "/case-studies/",
    "/case-studies/saas-pipeline-case-study/",
    "/case-studies/fintech-appointment-setting/",
    "/success/booking-confirmed/",
    "/success/contact-received/",
    "/success/subscribed/",
    "/privacy/",
    "/terms/",
    "/cookies/",
  ],
};
